name: Update Helm Values for ArgoCD Sync

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The Docker image tag to use (e.g., 0.0.1)"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      CHART_DEPLOYMENT_REPO: dounpct/argocd-azure-deployment
      CHART_DEPLOYMENT_BRANCH: master
      CD_CHART_REPO: argocd-azure-deployment
      CD_VAULE_FILE: applications-deployment/devops-test-aure/values-prod.yaml

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Checkout chart deployment repo
      uses: actions/checkout@v3
      with:
        repository: ${{ env.CHART_DEPLOYMENT_REPO }}
        ref: ${{ env.CHART_DEPLOYMENT_BRANCH }}
        path: ${{ env.CD_CHART_REPO }}
        fetch-depth: 0
        token: ${{ secrets.GIT_TOKEN }}

    - name: Update image tag in values.yaml
      run: |
        cd ${{ env.CD_CHART_REPO }}
        ls -alrt
        sed -i 's|^\( *tag:\).*|\1 "'"${{ github.event.inputs.tag }}"'"|' ${{ env.CD_VAULE_FILE }}
        echo "Updated imageTag to ${{ github.event.inputs.tag }}"
      shell: bash

    - name: Commit and push changes
      run: |
        cd ${{ env.CD_CHART_REPO }}
        git config user.name "dounpct"
        git config user.email "doun_pct@hotmail.com"
        git add ${{ env.CD_VAULE_FILE }}
        git commit -m "Update image tag to ${{ github.event.inputs.tag }}"
        git push