name: Update Helm Values for ArgoCD Sync

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The Docker image tag to use (e.g., 0.0.1)"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Clone target repository
      run: |
        git clone https://github.com/dounpct/argocd-azure-deployment.git
        cd argocd-azure-deployment
        echo "Repository cloned successfully"

    - name: Update image tag in values.yaml
      working-directory: argocd-azure-deployment/applications-deployment/devops-test-aure
      run: |
        sed -i 's|^\( *tag:\).*|\1 "'"${{ github.event.inputs.tag }}"'"|' values-prod.yaml
        echo "Updated imageTag to ${{ github.event.inputs.tag }}"

    - name: Commit and push changes
      working-directory: argocd-azure-deployment/applications-deployment/devops-test-aure
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "dounpct"
        git config user.email "doun_pct@hotmail.com"
        ls -lart
        cat values-prod.yaml
        git add values-prod.yaml
        git commit -m "Update image tag to ${{ github.event.inputs.tag }}"
        git push

    # - name: Update Helm values file
    #   run: |
    #     HELM_VALUES_FILE="helm/values.yaml"  # Path to your Helm values file
    #     IMAGE_TAG="${{ github.event.inputs.tag }}"
    #     sed -i "s|image:.*|image: my-app:${IMAGE_TAG}|g" $HELM_VALUES_FILE
    #     git config user.name "github-actions"
    #     git config user.email "github-actions@github.com"
    #     git add $HELM_VALUES_FILE
    #     git commit -m "Update Helm values with image tag: ${IMAGE_TAG}"
    #     git push